FROM node:18-alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
# COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY /nginx/nginx_gcloud.conf /etc/nginx/conf.d/defalut.conf
CMD []
EXPOSE 80
