steps:
  # Step 1: Build images using Docker Compose
  - name: 'docker/compose:latest'
    id: 'Build with Docker Compose'
    args: ['build']

  # Step 2: Tag the api service image for GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Tag api image for GCR'
    args: [
      'tag', 'backend', 'gcr.io/$PROJECT_ID/flightchat-api:latest'
    ]

  # Step 3: Tag the web service image for GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Tag web image for GCR'
    args: [
      'tag', 'frontend', 'gcr.io/$PROJECT_ID/flightchat-app:latest'
    ]

  # Step 4: Push the api service image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push api image to GCR'
    args: [
      'push', 'gcr.io/$PROJECT_ID/my-app-api:latest'
    ]

  # Step 5: Push the web service image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push web image to GCR'
    args: [
      'push', 'gcr.io/$PROJECT_ID/my-app-web:latest'
    ]

  # Step 6: Deploy the api service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy api service to Cloud Run'
    args: [
      'run', 'deploy', 'flightchat-api-service',
      '--image', 'gcr.io/$PROJECT_ID/flightchat-api:latest',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  # Step 7: Wait for the api service to be ready
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Wait for api service to be ready'
    args: [
      'run', 'services', 'describe', 'flightchat-api-service',
      '--platform', 'managed',
      '--format', 'value(status.url)'
    ]
    waitFor: ['Deploy api service to Cloud Run']

  # Step 8: Deploy the web service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy web service to Cloud Run'
    args: [
      'run', 'deploy', 'flightchat-app-service',
      '--image', 'gcr.io/$PROJECT_ID/flightchat-app:latest',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

# Optional: Specify the Docker registry for images
images:
  - 'gcr.io/$PROJECT_ID/flightchat-app:latest'
  - 'gcr.io/$PROJECT_ID/flightchat-api:latest'
options:
  env:
    - 'CLOUD_LOGGING_ONLY=TRUE'