version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - OPENAI_API_KEY='sk-2dc32749ec674c3ba0a6e06f7071797c'
      - LLM_URL='https://api.deepseek.com/v1'
      - LLM_MODEL='deepseek-chat'
      - DB_HOST='able-folio-453710-a6:europe-west3:flight-db'
      - DB_NAME='flights'
      - DB_USER='flight'
      - DB_PASSWORD='123456'
      - DB_PORT=5432
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

