# 使用较小的Python基础镜像
FROM python:3.13-slim

# 设置工作目录
WORKDIR /app
ENV PYTHONPATH="/app"

# 复制依赖文件，并安装依赖
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 将代码复制到容器中
COPY . .

# 暴露FastAPI默认端口
EXPOSE 8000

# 启动uvicorn服务器
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


